version: "3.5"
services:
  telegraf:
    image: telegraf:1.9.5-alpine
    hostname: telegraf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/docker/telegraf/data:/var/lib/telegraf"
      - "/var/docker/telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - online
networks:
  online:
    external: true
    name: online
